version: "1.0"
services:
  frontend:
    image: node:latest
    container_name: ton-link-frontend
    build:
      context: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm run start

  backend:
    image: node:latest
    container_name: ton-link-backend
    build:
      context: backend  
    ports:
      - "80:80"
    command: node /root/back/index.js
  node:
    image: node:latest
    container_name: ton-link-node
    build:
      context: client
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: ton-link-database
    environment:
      POSTGRES_DB: "tonlink_db"
      POSTGRES_USER: "tonlink"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
